<a href="https://colab.research.google.com/github/DeveloperSahil2001/Machine_Learning/blob/main/KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from google.colab import files
uploaded = files.upload()

Saving Churn_Modelling.csv to Churn_Modelling.csv


Saving Churn_Modelling.csv to Churn_Modelling (1).csv


In [4]:
data = pd.read_csv('Churn_Modelling.csv')
data.head(10)

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0
5          6    15574012       Chu  ...               0       149756.71      1
6          7    15592531  Bartlett  ...               1        10062.80      0
7          8    15656148    Obinna  ...               0       119346.88      1
8          9    15792365        He  ...               1        74940.50      0
9         10    15592389        H?  ...               1        71725.73      0

[10 rows x 14 columns]

In [7]:
real_x=data.iloc[:,[3,6,12]].values
real_y=data.iloc[:,12].values

In [8]:
train_x,test_x,train_y,test_y=train_test_split(real_x,real_y,test_size=0.5,random_state=0)
train_x

array([[5.8400000e+02, 3.0000000e+01, 1.7777203e+05],
       [7.2600000e+02, 3.8000000e+01, 1.2805229e+05],
       [5.7700000e+02, 3.4000000e+01, 8.4033350e+04],
       ...,
       [7.3800000e+02, 3.5000000e+01, 1.8142987e+05],
       [5.9000000e+02, 3.8000000e+01, 1.4875016e+05],
       [6.2300000e+02, 4.8000000e+01, 1.1885526e+05]])

In [14]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
train_x=sc.fit_transform(train_x)
test_x=sc.fit_transform(test_x)

In [15]:
from sklearn.neighbors import KNeighborsRegressor

In [16]:
cls = KNeighborsRegressor(n_neighbors=5, weights='uniform', algorithm='auto', leaf_size=30, p=2, metric='minkowski', metric_params=None, n_jobs=1)

In [17]:
cls.fit(train_x, train_y)
y_pred=cls.predict(test_x)
y_pred

array([191291.47 , 130505.454,  73351.41 , ..., 132965.702,  30756.098,
       125630.724])

In [18]:
test_y

array([192852.67, 128702.1 ,  75732.25, ..., 137041.26,  32996.89,
       125305.34])