<a href="https://colab.research.google.com/github/DeveloperSahil2001/Machine_Learning/blob/main/SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from google.colab import files
uploaded = files.upload()

Saving weight-height.csv to weight-height.csv


In [ ]:
data=pd.read_csv('weight-height.csv')
data.head(10)

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801
5   Male  67.253016  152.212156
6   Male  68.785081  183.927889
7   Male  68.348516  167.971110
8   Male  67.018950  175.929440
9   Male  63.456494  156.399676

In [ ]:
dummy=pd.get_dummies(data['Gender'])
dummy.head(10)

Female  Male
0       0     1
1       0     1
2       0     1
3       0     1
4       0     1
5       0     1
6       0     1
7       0     1
8       0     1
9       0     1

In [ ]:
df2=pd.concat((data,dummy),axis=1)
df2.head()

Gender     Height      Weight  Female  Male
0   Male  73.847017  241.893563       0     1
1   Male  68.781904  162.310473       0     1
2   Male  74.110105  212.740856       0     1
3   Male  71.730978  220.042470       0     1
4   Male  69.881796  206.349801       0     1

In [ ]:
df2=df2.drop(['Gender'],axis=1)
df2.head()

Height      Weight  Female  Male
0  73.847017  241.893563       0     1
1  68.781904  162.310473       0     1
2  74.110105  212.740856       0     1
3  71.730978  220.042470       0     1
4  69.881796  206.349801       0     1

In [ ]:
df2=df2.drop(['Male'],axis=1)
df2.head()

Height      Weight  Female
0  73.847017  241.893563       0
1  68.781904  162.310473       0
2  74.110105  212.740856       0
3  71.730978  220.042470       0
4  69.881796  206.349801       0

In [ ]:
df2.rename(columns={"Female":"Gender"})

Height      Weight  Gender
0     73.847017  241.893563       0
1     68.781904  162.310473       0
2     74.110105  212.740856       0
3     71.730978  220.042470       0
4     69.881796  206.349801       0
...         ...         ...     ...
9995  66.172652  136.777454       1
9996  67.067155  170.867906       1
9997  63.867992  128.475319       1
9998  69.034243  163.852461       1
9999  61.944246  113.649103       1

[10000 rows x 3 columns]

In [ ]:
real_x=df2.iloc[:,[0,1]].values
real_y=df2.iloc[:,2].values

In [ ]:
train_x,test_x,train_y,test_y=train_test_split(real_x,real_y,test_size=0.2,random_state=0)

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
s_c=StandardScaler()
train_x=s_c.fit_transform(train_x)
test_x=s_c.fit_transform(test_x)
train_x

array([[-1.82162984, -1.33285162],
       [-0.63969087, -0.14847181],
       [ 1.74026908,  1.54444689],
       ...,
       [ 0.28292964,  0.02903751],
       [-1.10459869, -0.7714607 ],
       [ 1.0962628 ,  0.83831503]])

In [ ]:
from sklearn.svm import SVC

In [ ]:
cls_svc=SVC(kernel='linear',random_state=0)
cls_svc.fit(train_x,train_y)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [ ]:
y_pred=cls_svc.predict(test_x)
y_pred

array([1, 0, 0, ..., 1, 0, 0], dtype=uint8)

In [ ]:
test_y

array([1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
cm=confusion_matrix(test_y,y_pred)
cm

array([[911,  77],
       [ 82, 930]])